### ISSUE TITLE
Negative numbers in Wombat crashes GH

### ISSUE THREAD

**Issue by FlynnAD** [woodsbagot/WombatGH#13]
**Issue/ Bug**
If you try to use the Wombat node "Decimal-Foot to Foot-Inch" within Grasshopper, and the numbers or dimensions that you are using happen to be negative (for example, you have a point that is on a negative x-axis) then inserting this negative value into the Wombat Grasshopper node will crash Grasshopper.

**To Reproduce**
1. Make a point in Rhino someplace in a negative axis (say the negative x-axis).
2. Reference that point into Grasshopper.
2b. Explode that point into x,y,z values.
3. Place the Wombat command of "Decimal Foot to Foot-Inch" node onto your Grasshopper screen.
3b. Right click on the A-slot of the Wombat node, and choose to use 1/8 inch increments.
4. Plug in the X-value (which is negative) of the exploded x,y,z point into the Wombat V-slot.
5. Grasshopper crashes.

**Expected behavior**
Wombat should return the Fractional Feet-Inches but with a negative sign.

**Screenshots**

**Additional context**
The current workaround is to make all the values absolute before you insert them into the V slot of the Wombat Grasshopper node, then use a zero-minus node to place them back into negative value.

Sincerely,
Matt Flynn/ general@flynn-design.com

**Comment by andrewheumann** [comment]
Just wanted to bump this one as it came up again https://discourse.mcneel.com/t/crash-report/105952

**Comment by Dre-Tas** [comment]
@FlynnAD this should be fixed in the code I just pushed. Thanks for letting us know and sorry if it took us a while.

We're about to release the updated plugin on food4rhino.
