### ISSUE TITLE
Plugin Version defined in WombatGHInfo not consistent with AssemblyVersion

### ISSUE THREAD

**Issue by snabela** [woodsbagot/WombatGH#24]
**Describe the bug**
Plugin Version defined in `WombatGHInfo` not consistent with `AssemblyVersion`

**To Reproduce**
Save a GH model which makes use of at least one component of Wombat using the XML format (`.ghx`). The following version information is reported: 

```
        <chunk name="GHALibraries">
          <items count="1">
            <item name="Count" type_name="gh_int32" type_code="3">1</item>
          </items>
          <chunks count="1">
            <chunk name="Library" index="0">
              <items count="6">
                <item name="AssemblyFullName" type_name="gh_string" type_code="10">WombatGH, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null</item>
                <item name="AssemblyVersion" type_name="gh_string" type_code="10">1.3.1.0</item>
                <item name="Author" type_name="gh_string" type_code="10">Woods Bagot Design Technology</item>
                <item name="Id" type_name="gh_guid" type_code="9">ce132bbb-4e91-42da-88c9-14a6f5da87c6</item>
                <item name="Name" type_name="gh_string" type_code="10">Wombat</item>
                <item name="Version" type_name="gh_string" type_code="10">1.1.0.0</item>
              </items>
            </chunk>
          </chunks>
        </chunk>
```

It might be that `Version` is kept out of sync with `AssemblyVersion` on purpose, but most likely it was just forgotten. This may cause problems with checking whether Grasshopper models saved using older versions of Wombat can still be opened with full backward compatibility by newer versions of Wombat. Ideally `Version` and `AssemblyVersion` would be in sync. 

**How to fix this**
`AssemblyVersion` is defined here: https://github.com/woodsbagot/WombatGH/blob/52931febeddf0757f5150b69dc3287f271ca8618/WombatGH/Properties/AssemblyInfo.cs#L36
`Version` is defined here: https://github.com/woodsbagot/WombatGH/blob/52931febeddf0757f5150b69dc3287f271ca8618/WombatGH/WombatGHInfo.cs#L20

Simple fix to keep the `Version` and the `AssemblyVersion` defined in [`WombatGHInfo.cs`](https://github.com/woodsbagot/WombatGH/blob/master/WombatGH/WombatGHInfo.cs) in sync with [`AssemblyInfo.cs`](https://github.com/woodsbagot/WombatGH/blob/master/WombatGH/Properties/AssemblyInfo.cs):

```
        public override string Version
        {
            get
            {
                var version = Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyVersionAttribute>().Version;
                return version.ToString();
            }
        }

        public override string AssemblyVersion
        {
            get
            {
                var version = Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyVersionAttribute>().Version;   
                return version.ToString();
            }
        }
```

**Comment by snabela** [comment]
@shaneburger Please let me know whether you prefer a PR for this fix.

**Comment by Dre-Tas** [comment]
@snabela absolutely, feel free to push a PR. I like your solution to keep them in sync!

**Comment by snabela** [comment]
@Dre-Tas great, there you go 😁 
https://github.com/woodsbagot/WombatGH/pull/25

**Comment by Dre-Tas** [comment]
Thanks @snabela it looks great!
I just need to get the right account to approve the merge and it will all be done. I'll let you know when it's done ;)

**Comment by snabela** [comment]
Many thanks @Dre-Tas !
