### ISSUE TITLE
Better icons?

### ISSUE THREAD

**Issue by zohozer** [woodsbagot/WombatGH#26]
Hi. I just discovered this GH components and I want to use some of them but I do think that the colour of the icons are very bad. Everything black, don't match the clasic GH color icons.

It is possible to create more classic style GH icons for this components? Maybe an inverse colour filter aplied to them will do the trick?

Best regards.

**Comment by zohozer** [comment]
I do created a version of icons that are much better readable by iverting the colours of the original ones. It is possible to compile Wombat with this icons?

[Resources.zip](https://github.com/woodsbagot/WombatGH/files/9742427/Resources.zip)

**Comment by Dre-Tas** [comment]
Hi @zohozer 
I'm sorry to hear you don't enjoy our icons. They follow our Woods Bagot colour coding convention, so they're consistent with all our other internal and external tools.
Unfortunately I understand the subjectivity of aesthetics and what is "very bad" for you is fine with us and many others.

This said, rest assured the components work like a charm (as far as we know) and functionality is not related to the look of the icons ;)

Also, I'm glad you managed to find a version of the icons you like better! Another point to open source.
