### ISSUE TITLE
Join Curves with Tolerance - allow user to choose join method

### ISSUE THREAD

**Issue by EPrang** [woodsbagot/WombatGH#3]
Actually your Join curve with tolerance move the curve end (or start). I think it will be interesting to have a joint curve, not moving the curve. For that you need to extend the curves.
This command exist in Rhino "Connect", but I didn't find it in grasshoper. The option of the connection can be line, arc ... and may be a limit distance ...
Many thanks for your good job
Eric

**Comment by mswaidan** [comment]
Thanks for the suggestion @EPrang ! Right now the CloseCurve component doesn't move the curve, but draws a line between start/end points. I agree it would be great to let the user decide how the curve gets closed though, so I'm going to mark this as an enhancement and will address it before the next release.

**Comment by mswaidan** [comment]
@EPrang Thanks for the suggestion! I agree it would be great to let the user choose how curves are joined. Will mark this as enhancement and address it before the next release, unless you (or someone else!) wants to open an PR to address it first.

**Comment by mswaidan** [comment]
@EPrang: #10 from @chepilot adds linear extension option instead of moving endpoints.
